
[common]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_port = COM3
lib_deps =
    ottowinter/ESPAsyncWebServer-esphome @ ^3.1.0
    paulstoffregen/OneWire @ ^2.3.7
    milesburton/DallasTemperature @ ^3.9.0
    knolleary/PubSubClient @ ^2.8

[env:esp32dev]
extends = common
upload_port = COM3
upload_speed = 921600
