
[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

board_build.flash_size = 16MB
board_build.psram_type = opi

board_build.partitions = partitions_16mb_ota.csv

lib_deps =
    ottowinter/ESPAsyncWebServer-esphome @ ^3.1.0
    paulstoffregen/OneWire @ ^2.3.7
    milesburton/DallasTemperature @ ^3.9.0
    knolleary/PubSubClient @ ^2.8
    adafruit/Adafruit NeoPixel @ ^1.12.0

build_src_filter = -<main.cpp> -<motor_n20_test.cpp> +<main_s3.cpp>
upload_port = COM6
